### ISSUE TITLE
[NEWS] Failed to update rogered users

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#101]
2017-02-09 10:47:27 UTC
xxx:be-hello-app
Count: 6 - Version: 0.2616

```java
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to read from field 'android.widget.LinearLayout com.mobicage.rogerthat.NewsListAdapter$ViewHolder.membersContainer' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.setupRogeredUsers(NewsListAdapter.java:917)
	at com.mobicage.rogerthat.NewsListAdapter.updateView(NewsListAdapter.java:319)
	at com.mobicage.rogerthat.NewsActivity$12.safeRun(NewsActivity.java:572)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)


mobicageVersion: 0.2616

occurenceCount: 6

platform: 1

platformVersion: asus/WW_Phone/ASUS_Z00VD:5.1/LMY47I/WW_Phone-12.1.0.47-20160404:user/release-keys (-) 22 (-) ASUS_Z00VD
```

**Comment by RubenMattan** [comment]
```java
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.mobicage.rogerthat.NewsListAdapter$ViewHolder.reach' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.updateView(NewsListAdapter.java:307)
	at com.mobicage.rogerthat.NewsActivity$14.safeRun(NewsActivity.java:604)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2616

occurenceCount: 1

platform: 1

platformVersion: samsung/zeroltebmc/zeroltebmc:6.0.1/MMB29K/G925W8VLU5CPK4:user/release-keys (-) 23 (-) SM-G925W8
```
