### ISSUE TITLE
App not build correctly

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#104]
2017-02-09 07:13:14 UTC
xxx:be-sint-truiden
Count: 6 - Version: 2.0.2660.A

```java
description: Uncaught exception

errorMessage: java.lang.RuntimeException: Unable to create application com.mobicage.rogerthat.App: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1800(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at org.altbeacon.beacon.BeaconManager.verifyServiceDeclaration(BeaconManager.java:755)
	at org.altbeacon.beacon.BeaconManager.<init>(BeaconManager.java:225)
	at org.altbeacon.beacon.BeaconManager.getInstanceForApplication(BeaconManager.java:217)
	at org.altbeacon.beacon.powersave.BackgroundPowerSaver.<init>(BackgroundPowerSaver.java:43)
	at org.altbeacon.beacon.powersave.BackgroundPowerSaver.<init>(BackgroundPowerSaver.java:53)
	at com.mobicage.rogerthat.App.onCreate(App.java:82)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6428)
	... 8 more


mobicageVersion: 2.0.2660.A

occurenceCount: 6

platform: 1

platformVersion: 23
```

**Comment by RubenMattan** [comment]
```python

description: Uncaught exception

errorMessage: java.lang.RuntimeException: Unable to create application com.mobicage.rogerthat.App: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1800(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7331)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: org.altbeacon.beacon.BeaconManager$ServiceNotDeclaredException: The BeaconService is not properly declared in AndroidManifest.xml.  If using Eclipse, please verify that your project.properties has manifestmerger.enabled=true
	at org.altbeacon.beacon.BeaconManager.verifyServiceDeclaration(BeaconManager.java:755)
	at org.altbeacon.beacon.BeaconManager.<init>(BeaconManager.java:225)
	at org.altbeacon.beacon.BeaconManager.getInstanceForApplication(BeaconManager.java:217)
	at org.altbeacon.beacon.powersave.BackgroundPowerSaver.<init>(BackgroundPowerSaver.java:43)
	at org.altbeacon.beacon.powersave.BackgroundPowerSaver.<init>(BackgroundPowerSaver.java:53)
	at com.mobicage.rogerthat.App.onCreate(App.java:82)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6428)
	... 8 more


mobicageVersion: 2.0.2849.A

occurenceCount: 12

platform: 1

platformVersion: 23
```

**Comment by RubenMattan** [comment]
could not reproduce with version 2.0.2849
