### ISSUE TITLE
Failed to execute mfr

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#109]
2017-02-10 06:48:10 UTC
xxx:be-merchtem
Count: 2 - Version: 0.2646

```java
description: Bug!
JsMfr Exception

errorMessage: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at java.util.regex.Matcher.reset(Matcher.java:177)
	at java.util.regex.Matcher.<init>(Matcher.java:90)
	at java.util.regex.Pattern.matcher(Pattern.java:297)
	at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$1.safeRun(JsMfr.java:279)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 0.2646

occurenceCount: 2

platform: 1

platformVersion: Huawei/ALE-L21/hwALE-H:6.0/HuaweiALE-L21/C432B584:user/release-keys (-) 23 (-) ALE-L21
```

**Comment by bart-at-mobicage** [comment]
Happened again

2017-03-20 08:07:21 UTC
   (1 hour(s) ago)
xxx@telenet.be:be-loc
Count: 1 - Version: 0.2725

**Comment by RubenMattan** [comment]
duplicate of https://github.com/rogerthat-platform/rogerthat-android-client/issues/172
