### ISSUE TITLE
Error while setting app colors on Huawei P8lite

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#121]
description: None

errorMessage: `java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar)`
```
	at java.lang.Class.getDeclaredField(Native Method)
	at com.mobicage.rogerthat.util.ui.UIUtils.colorEditText(UIUtils.java:811)
	at com.mobicage.rogerthat.util.ui.UIUtils.setCursorColor(UIUtils.java:833)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColors(UIUtils.java:887)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColors(UIUtils.java:858)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:917)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.util.ui.UIUtils.setColorsRecursive(UIUtils.java:919)
	at com.mobicage.rogerthat.ServiceBoundActivity.setContentView(ServiceBoundActivity.java:526)
	at com.mobicage.rogerthat.NewsActivity.onCreate(NewsActivity.java:101)
	at android.app.Activity.performCreate(Activity.java:6367)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
	at android.app.ActivityThread.access$900(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

mobicageVersion: 0.2736

occurenceCount: 164

platform: 1

platformVersion: Huawei/ALE-L21/hwALE-H:6.0/HuaweiALE-L21/C432B584:user/release-keys (-) 23 (-) ALE-L21

**Comment by bart-at-mobicage** [comment]
duplicate: #119
