### ISSUE TITLE
NullPointerException in ServiceBoundActivity

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#122]
```
2017-03-20 08:14:01 UTC
   (1 hour(s) ago)
***@pandora.be:be-beveren
Count: 1 - Version: 0.2749

description: Bug!
Error in SafeBroadcastReceiver

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackground(android.graphics.drawable.Drawable)' on a null object reference
	at com.mobicage.rogerthat.ServiceBoundActivity.showNavigationToolbar(ServiceBoundActivity.java:535)
	at com.mobicage.rogerthat.ServiceBoundActivity.access$200(ServiceBoundActivity.java:92)
	at com.mobicage.rogerthat.ServiceBoundActivity$1.onSafeReceive(ServiceBoundActivity.java:121)
	at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:997)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2787

occurenceCount: 8

platform: 1

platformVersion: samsung/a3xeltexx/a3xelte:6.0.1/MMB29K/A310FXXU2BQA3:user/release-keys (-) 23 (-) SM-A310F
```

**Comment by bart-at-mobicage** [comment]
```
2017-06-28 07:42:58 UTC
   (3 min ago)
***@telenet.be:be-sint-truiden
Count: 3 - Version: 0.2849

description: Bug!
Error in SafeBroadcastReceiver

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackground(android.graphics.drawable.Drawable)' on a null object reference
	at com.mobicage.rogerthat.ServiceBoundActivity.showNavigationToolbar(ServiceBoundActivity.java:535)
	at com.mobicage.rogerthat.ServiceBoundActivity.access$200(ServiceBoundActivity.java:92)
	at com.mobicage.rogerthat.ServiceBoundActivity$1.onSafeReceive(ServiceBoundActivity.java:121)
	at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:997)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7303)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2849

occurenceCount: 3

platform: 1

platformVersion: samsung/gtaxlwifixx/gtaxlwifi:6.0.1/MMB29K/T580XXU2AQA2:user/release-keys (-) 23 (-) SM-T580
```
