### ISSUE TITLE
NullPointerException in NewsActivity

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#123]
2017-03-20 07:43:52 UTC
   (2 hour(s) ago)
***@hotmail.com:em-be-***-demo
Count: 1 - Version: 0.2473

```
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.mobicage.rogerthat.NewsListAdapter$ViewHolder.reach' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.updateView(NewsListAdapter.java:307)
	at com.mobicage.rogerthat.NewsActivity$14.safeRun(NewsActivity.java:604)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2473

occurenceCount: 1

platform: 1

platformVersion: samsung/zeroltexx/zerolte:6.0.1/MMB29K/G925FXXS4DPJ5:user/release-keys (-) 23 (-) SM-G925F
```

Might be related to this error as well

```
description: Uncaught exception

errorMessage: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:2).state:6
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5011)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
	at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
	at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1596)
	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2704)
	at android.view.View.dispatchTouchEvent(View.java:9998)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2828)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2499)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2816)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4834)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4891)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7359)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7469)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7433)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7496)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:625)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 1.0.2473.A

occurenceCount: 1

platform: 1

platformVersion: 23
```

**Comment by bart-at-mobicage** [comment]
Happened more than once


2017-03-20 07:05:34 UTC
   (3 hour(s) ago)
***@gmail.com:be-***-app
Count: 1 - Version: 0.2616

```
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.mobicage.rogerthat.NewsListAdapter$ViewHolder.reach' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.updateView(NewsListAdapter.java:307)
	at com.mobicage.rogerthat.NewsActivity$14.safeRun(NewsActivity.java:604)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2616

occurenceCount: 1

platform: 1

platformVersion: samsung/nobleltezt/noblelte:6.0.1/MMB29K/N9208ZTU3BQB1:user/release-keys (-) 23 (-) SM-N9208
```

**Comment by RubenMattan** [comment]
related to #66
