### ISSUE TITLE
NullPointerException in content branding app

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#14]
```
description: Uncaught exception

errorMessage: java.lang.NullPointerException
    at com.mobicage.rogerthat.plugins.friends.ActionScreenActivity$7.onPageFinished(ActionScreenActivity.java:683)
    at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:276)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3773)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:529)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)


mobicageVersion: 1.0.2352.A

occurenceCount: 4

platform: 1

platformVersion: 10
```

```
2016-10-14 19:14:01 UTC
   (-696 min ago)
None
Count: 4 - Version: 1.0.2352.A
```

**Comment by RubenMattan** [comment]
This was a bot testing every activity
