### ISSUE TITLE
Failed to save settings (com.mobicage.to.system.SettingsTO)

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#159]
description: Bug!
Error during response processing for 997e7ab2-fb1b-4bf7-aa90-38540ab61351

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.mobicage.to.system.SettingsTO.<init>(SettingsTO.java:180)
	at com.mobicage.to.system.SaveSettingsResponse.<init>(SaveSettingsResponse.java:37)
	at com.mobicage.rpc.Parser.ComMobicageToSystemSaveSettingsResponse(Parser.java:2525)
	at com.mobicage.rpc.ResponseReceiverHandler.handle(ResponseReceiverHandler.java:716)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:253)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:175)
	at com.mobicage.rpc.http.HttpCommunicator$9$1.safeRun(HttpCommunicator.java:688)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)

mobicageVersion: 0.2840

occurenceCount: 263

platform: 1

platformVersion: acer/b3-a30_ww_gen1/acer_jetfirehd:6.0/MRA58K/1487768832:user/release-keys (-) 23 (-) B3-A30

**Comment by bart-at-mobicage** [comment]
#161
