### ISSUE TITLE
android.text.SpannedString cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#165]
```
2017-06-19 01:56:41 UTC
   (2 hour(s) ago)
***@gmail.com:be-sint-truiden
Count: 1 - Version: 0.2849
```

```
description: None

errorMessage: java.lang.ClassCastException: android.text.SpannedString cannot be cast to java.lang.String
	at com.mobicage.rogerthat.plugins.messaging.widgets.MyDigiPassWidget.proceedWithSubmit(MyDigiPassWidget.java:283)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.submitForm(ServiceMessageDetailActivity.java:904)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.buttonPressed(ServiceMessageDetailActivity.java:869)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.buttonPressed(ServiceMessageDetailActivity.java:861)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.buttonPressed(ServiceMessageDetailActivity.java:833)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.executeButtonClick(ServiceMessageDetailActivity.java:828)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.executeButtonClick(ServiceMessageDetailActivity.java:779)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity.access$800(ServiceMessageDetailActivity.java:110)
	at com.mobicage.rogerthat.plugins.messaging.ServiceMessageDetailActivity$10.safeOnClick(ServiceMessageDetailActivity.java:1004)
	at com.mobicage.rogerthat.util.system.SafeViewOnClickListener.onClick(SafeViewOnClickListener.java:32)
	at android.view.View.performClick(View.java:4452)
	at android.widget.Button.performClick(Button.java:148)
	at android.view.View$PerformClick.run(View.java:18428)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)


mobicageVersion: 0.2849

occurenceCount: 1

platform: 1

platformVersion: samsung/afyonltexx/afyonlte:4.2.2/JDQ39/G386FXXUANB5:user/release-keys (-) 17 (-) SM-G386F

```

**Comment by bart-at-mobicage** [comment]
already fixed
