### ISSUE TITLE
NullPointerException caused by GoogleServicesUtils

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#168]
```
2017-06-27 21:57:02 UTC
   (9 hour(s) ago)
***@greenitglobe.com:ae-veda
Count: 28 - Version: 0.3036
```

```
2017-06-27 21:53:21 UTC
   (9 hour(s) ago)
***@lovendegem.be:be-lovendegem
Count: 50 - Version: 0.3034
```

```
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.lang.StringBuilder.<init>(StringBuilder.java:110)
	at com.google.android.gms.gcm.GoogleCloudMessaging.zzf(Unknown Source)
	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
	at com.mobicage.rogerthat.util.GoogleServicesUtils$1.safeRun(GoogleServicesUtils.java:88)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 0.3036

occurenceCount: 28

platform: 1

platformVersion: samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXS1DQF6:user/release-keys (-) 24 (-) SM-G935F
```

**Comment by bart-at-mobicage** [comment]
GCM_DENDER_ID was missing in build.yaml of new apps. This is fixed in rogerthat-control-center.
