### ISSUE TITLE
NullPointerException in JsMfr

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#172]
```
2017-06-27 19:34:38 UTC
   (12 hour(s) ago)
ruben ***@itsyou.online:em-mobietrain
Count: 4 - Version: 0.2703

description: Bug!
JsMfr Exception

errorMessage: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at java.util.regex.Matcher.reset(Matcher.java:177)
	at java.util.regex.Matcher.<init>(Matcher.java:90)
	at java.util.regex.Pattern.matcher(Pattern.java:297)
	at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$1.safeRun(JsMfr.java:279)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 0.2703

occurenceCount: 4

platform: 1

platformVersion: samsung/a5xeltexx/a5xelte:6.0.1/MMB29K/A510FXXU4BQD1:user/release-keys (-) 23 (-) SM-A510F
```

**Comment by RubenMattan** [comment]
probably bug on startLocalFlow
