### ISSUE TITLE
Requesting plugin that is not yet initialized

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#174]
```
2017-06-27 13:52:19 UTC
   (18 hour(s) ago)
***@gmail.com:be-neerpelt
Count: 1 - Version: 0.2902

description: Bug!
Requesting plugin that is not yet initialized! class com.mobicage.rogerthat.plugins.news.NewsPlugin

errorMessage: java.lang.Exception
	at com.mobicage.rogerthat.util.logging.L.logToServer(L.java:151)
	at com.mobicage.rogerthat.util.logging.L.bug(L.java:114)
	at com.mobicage.rogerthat.MainService.getPlugin(MainService.java:1411)
	at com.mobicage.rogerthat.plugins.news.GetNewsResponseHandler.handle(GetNewsResponseHandler.java:51)
	at com.mobicage.rpc.ResponseReceiverHandler.handle(ResponseReceiverHandler.java:537)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:253)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:175)
	at com.mobicage.rpc.http.HttpCommunicator$9$1.safeRun(HttpCommunicator.java:688)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 0.2902

occurenceCount: 1

platform: 1

platformVersion: samsung/gt510wifixx/gt510wifi:6.0.1/MMB29M/T550XXU1BPK1:user/release-keys (-) 23 (-) SM-T550
```

**Comment by RubenMattan** [comment]
This only occurred in the Neerpelt app
