### ISSUE TITLE
StartFlowRequestTO is missing field 'flow_params'

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#187]
2017-07-11 07:10:20 UTC
   (4 hour(s) ago)
xxx:em-be-roi-booster
Count: 1 - Version: 0.3138

```java

errorMessage: com.mobicage.rpc.IncompleteMessageException: com.mobicage.to.messaging.StartFlowRequestTO object is missing field 'flow_params'
	at com.mobicage.to.messaging.StartFlowRequestTO.<init>(StartFlowRequestTO.java:71)
	at com.mobicage.rogerthat.plugins.messaging.StartFlowRequest.<init>(StartFlowRequest.java:33)
	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr$BrandedItem.<init>(BrandingMgr.java:244)
	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.readFromPickle(BrandingMgr.java:2082)
	at com.mobicage.rogerthat.util.pickle.Pickler.createObjectFromPickle(Pickler.java:59)
	at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.createBrandingMgr(BrandingMgr.java:473)
	at com.mobicage.rogerthat.MainService.createPlugins(MainService.java:901)
	at com.mobicage.rogerthat.MainService.setupServices(MainService.java:1055)
	at com.mobicage.rogerthat.MainService.initializeService(MainService.java:537)
	at com.mobicage.rogerthat.MainService.onCreate(MainService.java:320)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
	at android.app.ActivityThread.access$2100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.3138

occurenceCount: 1

platform: 1

platformVersion: samsung/trltexx/trlte:6.0.1/MMB29M/N910FXXS1DQE9:user/release-keys (-) 23 (-) SM-N910F
```

**Comment by bart-at-mobicage** [comment]
Newly added fields of RequestTO/ResponseTO object should always have a default value

```
diff --git a/src/rogerthat/to/messaging/__init__.py b/src/rogerthat/to/messaging/__init__.py
index f113104..5651e04 100644
--- a/src/rogerthat/to/messaging/__init__.py
+++ b/src/rogerthat/to/messaging/__init__.py
@@ -549,7 +549,7 @@ class StartFlowRequestTO(object):
                                                 doc="The client must download these attachments before starting the flow")
     parent_message_key = unicode_property('6')
     message_flow_run_id = unicode_property('7')
-    flow_params = unicode_property('8')
+    flow_params = unicode_property('8', default=None)
 
 
 class StartFlowResponseTO(object):
```

**Comment by RubenMattan** [comment]
Closing because this can't be fixed on the client
