### ISSUE TITLE
Database errors occur when the user follows/unfollows a service

### ISSUE THREAD

**Issue by abom** [rogerthat-platform/rogerthat-android-client#228]
Search services then follow any service, then go back or unfollow a service from the services list.

```
DEBUG    2017-09-04 12:17:16,982 logging_page.py:36] Error logged over HTTP:                                                               [127/12172]
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT f.rowid as _id, f.email, f.name, f.share_location, f
.shares_location, f.avatar, f.existence, f.type, f.description, f.description_branding, f.poke_description, f.qualified_identifier, f.organization_typ
e, f.callbacks, f.flags, f.profile_data, f.content_branding_hash, f.actions, IFNULL(c.id, f.email) AS cat_id, ifnull(c.name, f.name) AS cat_name, c.av
atar, count(f.email) FROM friend f LEFT OUTER JOIN friend_category c ON c.id = f.category_id WHERE (f.existence = 0 OR f.existence = 4) AND f.type = 2
 GROUP BY cat_id ORDER BY cat_name COLLATE NOCASE
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:163)
        at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:135)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:214)
        at android.widget.AlphabetIndexer.getSectionForPosition(AlphabetIndexer.java:257)
        at com.mobicage.rogerthat.FriendListAdapter.getSectionForPosition(FriendListAdapter.java:194)
        at android.widget.FastScroller.getPosFromItemCount(FastScroller.java:1265)
        at android.widget.FastScroller.onItemCountChanged(FastScroller.java:520)
        at android.widget.AbsListView.onLayout(AbsListView.java:2262)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1990)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1990)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1990)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1990)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
        at android.view.View.layout(View.java:16009)
        at android.view.ViewGroup.layout(ViewGroup.java:5181)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2483)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2180)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5660)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

```

**Comment by lucasvanhalst** [comment]
Can't reproduce this on android 7

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#48
