### ISSUE TITLE
UnrecoverableKeyException: Failed to obtain X.509 form of public key

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#244]
```
description: None

errorMessage: java.security.ProviderException: Failed to load generated key pair from keystore
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
	at com.mobicage.rogerthat.util.security.SecurityUtils.setupKeyStore(SecurityUtils.java:456)
	at com.mobicage.rogerthat.util.security.SecurityUtils.setPin(SecurityUtils.java:479)
	at com.mobicage.rogerthat.SetupPinActivity.onPinEntered(SetupPinActivity.java:91)
	at com.mobicage.rogerthat.widget.PinEntryView.sendKey(PinEntryView.java:90)
	at com.mobicage.rogerthat.widget.PinKeyboardView.setListener(PinKeyboardView.java:167)
	at com.mobicage.rogerthat.widget.PinKeyboardView.access$000(PinKeyboardView.java:30)
	at com.mobicage.rogerthat.widget.PinKeyboardView$13.onClick(PinKeyboardView.java:159)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22433)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6126)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
	... 18 more
Caused by: android.security.KeyStoreException: -22
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:666)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
	... 20 more


mobicageVersion: 1.3350

occurenceCount: 12

platform: 1

platformVersion: OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840920:user/release-keys (-) 25 (-) ONE A2003
```
[2017-09-18 17.55.29.mov.zip](https://github.com/rogerthat-platform/rogerthat-android-client/files/1311379/2017-09-18.17.55.29.mov.zip)

**Comment by RubenMattan** [comment]
Apps installed bitpay, atlant, coinomi, .... 
Branking app of keytrade

Android is rooted but is disabled and bootloader is unlocked

**Comment by RubenMattan** [comment]
![photo_2017-09-19_17-33-53](https://user-images.githubusercontent.com/1122760/30600840-c4f70188-9d60-11e7-885b-f4f26b78535a.jpg)

https://jira.lineageos.org/browse/BUGBASH-590?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
