### ISSUE TITLE
Unexpected form type: sign 

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#246]
Unexpected form type: sign 
```
java.lang.Exception
	at com.mobicage.rogerthat.util.logging.L.logToServer(L.java:151)
	at com.mobicage.rogerthat.util.logging.L.bug(L.java:114)
	at com.mobicage.rogerthat.plugins.messaging.widgets.Widget.valueString(Widget.java:172)
	at com.mobicage.rogerthat.plugins.messaging.ServiceThreadActivity$ServiceThreadAdapter.populateView(ServiceThreadActivity.java:321)
	at com.mobicage.rogerthat.plugins.messaging.ServiceThreadActivity$ServiceThreadAdapter.newView(ServiceThreadActivity.java:247)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:285)
	at android.widget.AbsListView.obtainView(AbsListView.java:3251)
	at android.widget.ListView.makeAndAddView(ListView.java:2147)
	at android.widget.ListView.fillUp(ListView.java:803)
	at android.widget.ListView.correctTooHigh(ListView.java:1547)
	at android.widget.ListView.fillSpecific(ListView.java:1485)
	at android.widget.ListView.layoutChildren(ListView.java:1877)
	at android.widget.AbsListView.onLayout(AbsListView.java:3021)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:935)
	at android.view.View.layout(View.java:18874)
	at android.view.ViewGroup.layout(ViewGroup.java:5954)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2697)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
	at android.view.Choreographer.doCallbacks(Choreographer.java:734)
	at android.view.Choreographer.doFrame(Choreographer.java:670)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
seppe_dobbelaere_1@itsyou.online:em-be-threefold-token @ 1505755283 (Monday, 18 September 2017 17:21:23)
mobicageVersion
 1.3368 
occurenceCount
 1 
platform
 1 
platformVersion
 samsung/dream2ltexx/dream2lte:7.0/NRD90M/G955FXXU1AQH3:user/release-keys (-) 24 (-) SM-G955F

**Comment by RubenMattan** [comment]
Will be fixed after we merge https://github.com/rogerthat-platform/rogerthat-android-client/pull/245
