### ISSUE TITLE
UTFDataFormatException in BramdingMgr: String more than 65535 UTF bytes long

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#285]
be-bree app: 2.1.3588.A

```
# Crashlytics - plaintext stacktrace downloaded by Bart Pede at Fri, 24 Nov 2017 08:55:53 GMT
# URL: https://fabric.io/gig-technology-nv/android/apps/com.mobicage.rogerthat.be.bree/issues/5a16f55161b02d480d17524e?time=last-seven-days/sessions/5A16F4A100D900012C6ACA20BA5E1CB5_3b39e4a1d06a11e78cdc56847afe9799_0_v2
# Organization:  GIG Technology NV.
# Platform: android
# Application: Bree
# Version: 2.1.3588.A (3588)
# Bundle Identifier: com.mobicage.rogerthat.be.bree
# Issue #: 1
# Issue ID: 5a16f55161b02d480d17524e
# Session ID: 5A16F4A100D900012C6ACA20BA5E1CB5_3b39e4a1d06a11e78cdc56847afe9799_0_v2
# Date: 2017-11-23T16:19:00Z
# OS Version: 6.0
# Device: P8 Lite
# RAM Free: 36.5%
# Disk Free: 5.4%

#0. Crashed: rogerthat_http_worker: 0 0 0x0000000000000000
       at com.mobicage.rogerthat.util.pickle.Pickler.getPickleFromObject(Pickler.java:79)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.save(BrandingMgr.java:1998)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:730)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:599)
       at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:691)
       at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newAdvancedOrderForm(MessagingCallReceiver.java:252)
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:70)
       at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$2.safeRun(JsMfr.java:373)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)

--

Non-fatal Exception: com.mobicage.rogerthat.util.pickle.PickleException: java.io.UTFDataFormatException: String more than 65535 UTF bytes long
       at com.mobicage.rogerthat.util.pickle.Pickler.getPickleFromObject(Pickler.java:79)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.save(BrandingMgr.java:1998)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:730)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:599)
       at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:691)
       at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newAdvancedOrderForm(MessagingCallReceiver.java:252)
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:70)
       at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$2.safeRun(JsMfr.java:373)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.io.UTFDataFormatException: String more than 65535 UTF bytes long
       at java.nio.charset.ModifiedUtf8.countBytes(ModifiedUtf8.java:86)
       at java.nio.charset.ModifiedUtf8.encode(ModifiedUtf8.java:119)
       at java.io.DataOutputStream.writeUTF(DataOutputStream.java:197)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.writePickle(BrandingMgr.java:2037)
       at com.mobicage.rogerthat.util.pickle.Pickler.getPickleFromObject(Pickler.java:76)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.save(BrandingMgr.java:1998)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:730)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:599)
       at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:691)
       at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newAdvancedOrderForm(MessagingCallReceiver.java:252)
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:70)
       at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$2.safeRun(JsMfr.java:373)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)

#0. Crashed: rogerthat_http_worker: 0 0 0x0000000000000000
       at com.mobicage.rogerthat.util.pickle.Pickler.getPickleFromObject(Pickler.java:79)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.save(BrandingMgr.java:1998)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:730)
       at com.mobicage.rogerthat.plugins.messaging.BrandingMgr.queue(BrandingMgr.java:599)
       at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:691)
       at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newAdvancedOrderForm(MessagingCallReceiver.java:252)
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:70)
       at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$2.safeRun(JsMfr.java:373)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#44
