### ISSUE TITLE
Attempt to read from field 'AppNewsItemTO.image_url' on a null object reference

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#286]
```
# Crashlytics - plaintext stacktrace downloaded by Bart Pede at Mon, 27 Nov 2017 08:35:29 GMT
# URL: https://fabric.io/gig-technology-nv/android/apps/com.mobicage.rogerthat.be.bree/issues/5a182fa061b02d480d2afca1?time=last-seven-days/sessions/5A17C0CF006300017A74268C8BF092C4_930e920cd12511e78cdc56847afe9799_7_v2
# Organization:  GIG Technology NV.
# Platform: android
# Application: Bree
# Version: 2.1.3588.A (3588)
# Bundle Identifier: com.mobicage.rogerthat.be.bree
# Issue #: 4
# Issue ID: 5a182fa061b02d480d2afca1
# Session ID: 5A17C0CF006300017A74268C8BF092C4_930e920cd12511e78cdc56847afe9799_7_v2
# Date: 2017-11-24T06:53:00Z
# OS Version: 7.1.1
# Device: ONEPLUS A5000
# RAM Free: 17.1%
# Disk Free: 72.9%

#0. Crashed: main: 0 0 0x0000000000000000
       at com.mobicage.rogerthat.NewsListAdapter$ViewHolder$1.onSafeReceive(NewsListAdapter.java:255)
       at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1167)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6334)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

--

Non-fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.mobicage.to.news.AppNewsItemTO.image_url' on a null object reference
       at com.mobicage.rogerthat.NewsListAdapter$ViewHolder$1.onSafeReceive(NewsListAdapter.java:255)
       at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1167)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6334)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

#0. Crashed: main: 0 0 0x0000000000000000
       at com.mobicage.rogerthat.NewsListAdapter$ViewHolder$1.onSafeReceive(NewsListAdapter.java:255)
       at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1167)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6334)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#43
