### ISSUE TITLE
NPE when processing updateJsEmbedding CAPI call

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#296]
java.lang.NullPointerException: Attempt to invoke interface method 'com.mobicage.to.js_embedding.UpdateJSEmbeddingResponseTO com.mobicage.capi.system.IClientRpc.updateJsEmbedding(com.mobicage.to.js_embedding.UpdateJSEmbeddingRequestTO)' on a null object reference

```
description: None

errorMessage: java.lang.NullPointerException: Attempt to invoke interface method 'com.mobicage.to.js_embedding.UpdateJSEmbeddingResponseTO com.mobicage.capi.system.IClientRpc.updateJsEmbedding(com.mobicage.to.js_embedding.UpdateJSEmbeddingRequestTO)' on a null object reference
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:217)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
	at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 1.3529

occurenceCount: 1

platform: 1

platformVersion: samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXU1DQJ1:user/release-keys (-) 24 (-) SM-G935F
```

```
description: Error returned as result of client call:
{"a":{"request":{"items":[{"hash":"A982D26D7BCE6E2C5D2CEB4BD3C64FE1F0DD212300041C495CAC9095891A9D30","name":"font-awesome"},{"hash":"3AACEFC84492F816F9A9481B8B0AD1423841B38F11CD0AE49127A0F79D05A91A","name":"jquery"},{"hash":"4B77B87FF6C7247E3E76B9502D31EDB736C259D87F7114A8AE6AE418F62EEEAF","name":"rogerthat"}]}},"ci":"034160eb-e658-11e7-b54f-dd585c1b5324","f":"com.mobicage.capi.system.updateJsEmbedding","t":1513865134,"av":1}

errorMessage: null
java.lang.NullPointerException
	at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:217)
	at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
	at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
	at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:175)
	at android.os.HandlerThread.run(HandlerThread.java:60)


mobicageVersion: 1.3535

occurenceCount: 1

platform: 4

platformVersion: 
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#41
