### ISSUE TITLE
NPE when calling cleanupOldBrandings

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#312]
```
2018-01-19 10:19:26 UTC
   (21 min ago)
6f85de93-1cf0-4fcf-8109-8c8d68e880db
Count: 5 - Version: 2.1.3597.A
```

```
description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mobicage.rogerthat.plugins.friends.FriendsPlugin.cleanupOldBrandings()' on a null object reference
	at com.mobicage.rogerthat.MainService$10.safeRun(MainService.java:1086)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)


mobicageVersion: 2.1.3597.A

occurenceCount: 5

platform: 1

platformVersion: 26
```

**Comment by RubenMattan** [comment]
What app_id is this?

**Comment by bart-at-mobicage** [comment]
No idea, you'll have to check jenkins

**Comment by lucasvanhalst** [comment]
I'ts be-borgloon

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#40
