### ISSUE TITLE
App crashes because app data is corrupt

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#320]
The user reported the following via app review: _"De app start niet meer op, al diverse keren opnieuw geïnstalleerd, Samsung galaxy s7"_

user (encrypted): `7707ab40cc190a026efa637a467a50d9:be-bree`

```
{'client_error': {'installId': None,
                  'timestamp': 1517126596L,  # Sun Jan 28 08:03:16 2018
  'description': u'Uncaught exception',
  'mobicageVersion': u'2.1.3629.A',
  'occurenceCount': 41L,
  'platform': 1L,
  'platformVersion': u'24'},
```

```
java.lang.ClassCastException: java.lang.String cannot be cast to org.json.simple.JSONArray
	at com.mobicage.rogerthat.plugins.friends.FriendStore.getDisabledBroadcastTypes(FriendStore.java:2005)
	at com.mobicage.rogerthat.plugins.friends.FriendsPlugin.isBroadcastTypeDisabled(FriendsPlugin.java:1544)
	at com.mobicage.rogerthat.NewsListAdapter$ViewHolder.populateView(NewsListAdapter.java:484)
	at com.mobicage.rogerthat.NewsListAdapter$ViewHolder.setNewsItem(NewsListAdapter.java:423)
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:1109)
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:88)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:822)
	at android.view.View.layout(View.java:18799)
	at android.view.ViewGroup.layout(ViewGroup.java:5952)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2634)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2350)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1509)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7051)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:638)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by RubenMattan** [comment]
Can't find the origin of this bug so added some logging.
https://github.com/rogerthat-platform/rogerthat-android-client/pull/322
