### ISSUE TITLE
IllegalArgumentException when setInfo is called before service is bound

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#321]
```
 {'client_error': {'installId': None,
                   'timestamp': 1517080301L,  # Sat Jan 27 19:11:41 2018
                   'user': users.User(email='***@itsyou.online:em-be-threefold-token'),
                   'userStr': u'***@itsyou.online:em-be-threefold-token'},
  'description': u'Bug!\nException in SafeRunnable',
  'mobicageVersion': u'1.3632',
  'occurenceCount': 9L,
  'platform': 1L,
  'platformVersion': u'samsung/trltexx/trlte:6.0.1/MMB29M/N910FXXU1DPI1:user/release-keys (-) 23 (-) SM-N910F'},
 
```

```
java.lang.IllegalArgumentException: the bind value at index 1 is null
	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:176)
	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:212)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1393)
	at com.mobicage.rogerthat.plugins.friends.FriendStore.getUserData(FriendStore.java:1106)
	at com.mobicage.rogerthat.plugins.friends.FriendsPlugin.getRogerthatUserAndServiceInfo(FriendsPlugin.java:1470)
	at com.mobicage.rogerthat.cordova.RogerthatPlugin.setInfo(RogerthatPlugin.java:270)
	at com.mobicage.rogerthat.cordova.RogerthatPlugin.access$600(RogerthatPlugin.java:60)
	at com.mobicage.rogerthat.cordova.RogerthatPlugin$2.safeRun(RogerthatPlugin.java:146)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by RubenMattan** [comment]
Not related to service bound, but wallet that was loading user data. Was already fixed by https://github.com/rogerthat-platform/rogerthat-android-client/commit/ef0e3f61ec58a74329531f15b49361a57863f83e
