### ISSUE TITLE
NPE: Unable to resume OauthRegistrationActivity

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#327]
```
2018-02-01 07:54:08 UTC
   (17 min ago)
None
Count: 1 - Version: 2.1.3632.A
```

```
description: Uncaught exception

errorMessage: java.lang.RuntimeException: Unable to resume activity {com.mobicage.rogerthat.em.be.threefold.token/com.mobicage.rogerthat.registration.OauthRegistrationActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { act=com.mobicage.rogerthat.FINISHED_OAUTH launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.mobicage.rogerthat.em.be.threefold.token/com.mobicage.rogerthat.registration.OauthRegistrationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.mobicage.rogerthat.registration.AbstractRegistrationWizard.getTimestamp()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3788)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { act=com.mobicage.rogerthat.FINISHED_OAUTH launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.mobicage.rogerthat.em.be.threefold.token/com.mobicage.rogerthat.registration.OauthRegistrationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.mobicage.rogerthat.registration.AbstractRegistrationWizard.getTimestamp()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4481)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3762)
	... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.mobicage.rogerthat.registration.AbstractRegistrationWizard.getTimestamp()' on a null object reference
	at com.mobicage.rogerthat.registration.OauthRegistrationActivity.registerWithOauthCode(OauthRegistrationActivity.java:198)
	at com.mobicage.rogerthat.registration.OauthRegistrationActivity.onActivityResult(OauthRegistrationActivity.java:176)
	at android.app.Activity.dispatchActivityResult(Activity.java:7226)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
	... 11 more


mobicageVersion: 2.1.3632.A

occurenceCount: 1

platform: 1

platformVersion: 24
```

**Comment by RubenMattan** [comment]
The wizard can never be null, most likely this is a bot testing the app
