### ISSUE TITLE
NPE in PinLockMgr

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#328]
https://fabric.io/gig-technology-nv/android/apps/com.mobicage.rogerthat.em.be.threefold.token/issues/5a785d6f8cb3c2fa635a1d81?time=last-seven-days

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.mobicage.rogerthat.config.Configuration com.mobicage.rogerthat.config.ConfigurationProvider.getConfiguration(java.lang.String)' on a null object reference
       at com.mobicage.rogerthat.util.security.SecurityUtils.getConfiguration(SecurityUtils.java:407)
       at com.mobicage.rogerthat.util.security.SecurityUtils.isPinSet(SecurityUtils.java:466)
       at com.mobicage.rogerthat.plugins.security.PinLockMgr.canContinueToActivity(PinLockMgr.java:166)
       at com.mobicage.rogerthat.plugins.security.PinLockMgr.checkAskPin(PinLockMgr.java:112)
       at com.mobicage.rogerthat.plugins.security.PinLockMgr.onActivityStarted(PinLockMgr.java:73)
       at android.app.Application.dispatchActivityStarted(Application.java:205)
       at android.app.Activity.onStart(Activity.java:1155)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:595)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.mobicage.rogerthat.ServiceBoundActivity.onStart(ServiceBoundActivity.java:398)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
       at android.app.Activity.performStart(Activity.java:6302)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#39
