### ISSUE TITLE
Wrong email sent to server when switching between email and fb registration

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#329]
The request sent to `/unauthenticated/mobi/registration/register_device` contained email `***@ugent.com` which was used in the email based registration attempt. 

But the facebook account has email `***@hotmail.com`. This email should have been sent to the server in the `/unauthenticated/mobi/registration/register_device` request.

Server logs:
```
/unauthenticated/mobi/registration/register_device

UnicodeMultiDict([(u'version', u'3'), (u'registration_time', u'1518210347'), (u'device_id', u'e3586c00-4ed9-44fe-b026-94f4e9d54047'), (u'registration_id', u'49516484-5934-4442-af3f-86293da17cf5'), (u'signature', u'22CDB6FC292A5EC7F74455B9DF1198D7339CFA8575C5F733B8CF6E8297B0B2B7'), (u'email', u'***@ugent.com'), (u'platform', u'android'), (u'language', u'nl'), (u'country', u'BE'), (u'app_id', u'rogerthat'), (u'use_xmpp_kick', u'false'), (u'GCM_registration_id', u'APA91bHo9k_pGwuukVfX-By7y0C9G1HzSmKOxyJx_0sEjA0d_Efc3bSMhiG7b6zB2UK-RLCOpT6RfsL4I7m0sv3Zf1m5x-8Ln6ZIJmoluo_88wTSaRvOSKRZMAwCKdlN2uWip_TglW4J'), (u'hardware_model', u'Galaxy S6 (SM-G920F)'), (u'sim_carrier_name', u'')]) (/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/pages/register_mobile.py:748)

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/pages/register_mobile.py", line 787, in post
    azzert(registration.device_names)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/properties.py", line 52, in azzert
    sorted(sys._getframe(1).f_locals.iteritems()), str(error_message) + '\n  Locals: '))
```

Installation logs:
```
2018-02-09T21:04:55.000Z | Install id d8500d47-d117-410b-bd5d-6679688fbc50, Version 2.1.3709.A
...
2018-02-09T21:04:58.000Z | 'Use Facebook' button pressed
2018-02-09T21:05:00.000Z | Current device names: [u'SM-G920F']
2018-02-09T21:05:00.000Z | Creating facebook based profile & validating registration request
2018-02-09T21:05:00.000Z | Profile created & registration request validated.

2018-02-09T21:05:28.000Z | Installed from country: BELGIUM (BE)
2018-02-09T21:05:28.000Z | Resolving country from IP address: 178.50.81.173
2018-02-09T21:05:37.000Z | Installed from country: BELGIUM (BE)
2018-02-09T21:05:37.000Z | Resolving country from IP address: 178.50.81.173
2018-02-09T21:05:48.000Z | ***@ugent.com requested pin
2018-02-09T21:05:48.000Z | Sent email to ***@ugent.com with pin 3795

2018-02-09T21:07:02.000Z | 'Use Facebook' button pressed
2018-02-09T21:07:02.000Z | Creating facebook based profile & validating registration request
2018-02-09T21:07:03.000Z | Profile created & registration request validated.
2018-02-09T21:07:03.000Z | Current device names: [u'SM-G920F']
* ERROR HAPPENED HERE *

2018-02-09T21:07:16.000Z | Installed from country: BELGIUM (BE)
2018-02-09T21:07:16.000Z | Resolving country from IP address: 178.50.81.173
2018-02-09T21:07:18.000Z | Installed from country: BELGIUM (BE)
2018-02-09T21:07:18.000Z | Resolving country from IP address: 178.50.81.173
2018-02-09T21:07:26.000Z | ***@hotmail.com requested pin
2018-02-09T21:07:26.000Z | Sent email to ***@hotmail.com with pin 6124
2018-02-09T21:08:53.000Z | Current device names: [u'SM-G920F']
2018-02-09T21:08:53.000Z | Entered correct pin: 6124
2018-02-09T21:08:56.000Z | Continued with registering device, the following device 'Galaxy S6 (SM-G920F)' is registered and [u'SM-G920F'] are unregistered
2018-02-09T21:08:58.000Z | Registration successful.
```

**Comment by bart-at-mobicage** [comment]
Fixed by https://github.com/rogerthat-platform/rogerthat-android-client/commit/5c204313a4a350edddf29089f368565eed3a6b1c?
