### ISSUE TITLE
updateUserData api call sent with {"v": xxx}

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#330]
`be-sint-truiden` app, latest version (`2.1.3701`)

```
2018-02-12 13:44:57.705 CET
Request identity: ***@telenet.be:be-sint-truiden (android)
```
```
2018-02-12 13:44:58.121 CET
Error while executing updateUserData: Traceback (most recent call last): (/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/rpc/rpc.py:740)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/rpc/rpc.py", line 729, in _perform_call
    result[RESULT] = run(function, [], kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 180, in run
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/rpc/rpc.py", line 370, in wrapped
    return f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/api/services.py", line 291, in updateUserData
    set_user_data(service_identity_user, app_user, data, replace, must_be_friends=False)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/bizz/service/__init__.py", line 2656, in set_user_data
    set_user_data_object(service_identity_user, friend_user, data_dict, replace, must_be_friends)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 164, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/mcfw/rpc.py", line 142, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/bizz/service/__init__.py", line 2761, in set_user_data_object
    run_in_xg_transaction(trans, data_dict)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/utils/transactions.py", line 103, in run_in_xg_transaction
    return db.run_in_transaction_options(xg_on, function, *args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/add_1_monkey_patches.py", line 217, in wrapped
    r = run(transaction_guid)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/add_1_monkey_patches.py", line 197, in run
    return _orig_run_in_transaction_options(options, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2647, in RunInTransactionOptions
    ok, result = _DoOneTry(function, args, kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/api/datastore.py", line 2667, in _DoOneTry
    result = function(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180208t100343.407506684661597574/rogerthat/bizz/service/__init__.py", line 2725, in trans
    fsic.disabled_broadcast_types = full_json_dict[DISABLED_BROADCAST_TYPES_USER_DATA_KEY]
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 617, in __set__
    value = self.validate(value)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 3475, in validate
    raise BadValueError('Property %s must be a list' % self.name)
BadValueError: Property disabled_broadcast_types must be a list
```
...
```
2018-02-12 13:44:59.281 CET
[XX-OFFLOADv1] {
  "timestamp":1518439499,
  "request_data":{
  "a":[],
  "c":[{
    "a":{"request":{
      "hashed_tag":"aa7c6529f975a4e0e3c8acfaa0ec8a90b998b9500d8857281861b308750e50ed",
      "params":"{\"notifications\":[5,6,27,28]}",
      "id":6,
      "service":"service-6490e2f3-4451-46da-aa66-7cca8dfbc76e@rogerth.at",
      "method":"trash.setNotifications"
    }
  },
  "ci":"534ee8d3-eb79-428f-8787-55827149eae3",
  "av":1,
  "t":1518439496,
  "f":"com.mobicage.api.services.sendApiCall"
  },{
    "a":{
      "request":{
        "service":"service-6490e2f3-4451-46da-aa66-7cca8dfbc76e@rogerth.at",
        "keys":[],
        "data":null,
        "user_data":"{\"__rt__disabledBroadcastTypes\":\"{\\\"v\\\":[\\\"Nieuws\\\"]}\",\"trash\":{\"address\":\"***\",\"collections\":[{\"day\":7,\"month\":2,\"epoch\":1517961600,\"year\":2018,\"activity\":{\"image_url\":\"images/papier.png\",...
...
```

**Comment by bart-at-mobicage** [comment]
App version `2.1.3701`:
`description: Bug!
Failed to getDisabledBroadcastTypes for service 'service-6490e2f3-4451-46da-aa66-7cca8dfbc76e@rogerth.at' with data: "{\"v\":[\"Nieuws\"]}"`

App version `2.1.3693`:
`description: Bug!
Failed to getDisabledBroadcastTypes for service 'latapacanaria@***' with data: "{\"v\":[\"Dagschotels\",\"Nieuws\"]}"`
