### ISSUE TITLE
Execution time exceeded during message flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#353]
Doesn't look like we can do anything about it :/
Can we nuke rhino and replace with v8 engine?

appVersion: 2.1.3857
osVersion: 22
hardwareModel: HP Pro Slate 8

```
org.mozilla.javascript.EvaluatorException: Execution time exceeded (unnamed script#852)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Context.reportError(Context.java:913)
	at org.mozilla.javascript.Context.reportError(Context.java:931)
	at com.mobicage.rogerthat.plugins.messaging.mfr.SandboxContextFactory.observeInstructionCount(SandboxContextFactory.java:77)
	at org.mozilla.javascript.Context.observeInstructionCount(Context.java:2371)
	at org.mozilla.javascript.Interpreter.addInstructionCount(Interpreter.java:3179)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1989)
	at script.cloneObj(unnamed script:852)
	at script.cloneObj(unnamed script:844)
	at script.cloneObj(unnamed script:854)
	at script.cloneObj(unnamed script:844)
	at script.cloneObj(unnamed script:854)
	at script.cloneObj(unnamed script:854)
	at script.getFlowcodeLocals(unnamed script:294)
	at script.getNextStepMessage(unnamed script:618)
	at script.processMessageStep(unnamed script:604)
	at script.transition(unnamed script:803)
	at script.mc_run(unnamed script:934)
	at script.mc_run_ext(unnamed script:954)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at com.mobicage.rogerthat.plugins.messaging.mfr.SandboxContextFactory.doTopCall(SandboxContextFactory.java:86)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at com.mobicage.rogerthat.plugins.messaging.mfr.SandboxContextFactory.doTopCall(SandboxContextFactory.java:86)
	at com.mobicage.rogerthat.plugins.messaging.mfr.JsMfr$1.safeRun(JsMfr.java:310)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lucasvanhalst** [comment]
See #307 maybe

**Comment by bart-at-mobicage** [comment]
Another occurrence

app version: 2.1.3857
os version: 23
hardware model: SM-G389F (Samsung Galaxy Xcover 3 G389F)
