### ISSUE TITLE
Cropping doesn't work with pictures from gallery

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-android-client#357]
Tried to upload a screenshot (this is a PNG file)
```
Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
        at android.media.ExifInterface.<init>(ExifInterface.java:1112)
        at com.soundcloud.android.crop.CropUtil.getExifRotation(CropUtil.java:84)
        at com.soundcloud.android.crop.CropUtil.getExifRotation(CropUtil.java:77)
        at com.mobicage.rogerthat.util.IOUtils.compressPicture(IOUtils.java:258)
        at com.mobicage.rogerthat.plugins.messaging.widgets.PhotoUploadWidget.handleSelection(PhotoUploadWidget.java:361)
        at com.mobicage.rogerthat.plugins.messaging.widgets.PhotoUploadWidget.access$400(PhotoUploadWidget.java:88)
        at com.mobicage.rogerthat.plugins.messaging.widgets.PhotoUploadWidget$2.safeOnPostExecute(PhotoUploadWidget.java:301)
        at com.mobicage.rogerthat.plugins.messaging.widgets.PhotoUploadWidget$2.safeOnPostExecute(PhotoUploadWidget.java:262)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#36
