### ISSUE TITLE
Failed to show service action menu

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#370]
```java
Non-fatal Exception: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
       at java.util.ArrayList.add(ArrayList.java:483)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity$MyPagerAdapter.createPage(ServiceActionMenuActivity.java:713)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity$MyPagerAdapter.createCell(ServiceActionMenuActivity.java:718)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity$MyPagerAdapter.addMenuItemToCell(ServiceActionMenuActivity.java:740)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity$MyPagerAdapter.updateServiceMenu(ServiceActionMenuActivity.java:798)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity.populateScreen(ServiceActionMenuActivity.java:288)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity.onServiceBound(ServiceActionMenuActivity.java:204)
       at com.mobicage.rogerthat.ServiceBoundActivity$7.onServiceConnected(ServiceBoundActivity.java:312)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1691)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1720)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by RubenMattan** [comment]
I guess this happens when 1 page is completely fall_through
