### ISSUE TITLE
Callreceiver for services was null

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#372]
```java
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.mobicage.to.service.UpdateUserDataResponseTO com.mobicage.capi.services.IClientRpc.updateUserData(com.mobicage.to.service.UpdateUserDataRequestTO)' on a null object reference
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:205)
       at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
       at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
       at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#33
