### ISSUE TITLE
Failed to open webview

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#374]
```java
Non-fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://www.delijn.be }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1638)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
       at android.app.Activity.startActivityForResult(Activity.java:3457)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:3418)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:3660)
       at android.app.Activity.startActivity(Activity.java:3628)
       at com.mobicage.rogerthat.plugins.friends.MenuItemPresser.openLink(MenuItemPresser.java:362)
       at com.mobicage.rogerthat.plugins.friends.MenuItemPresser.itemPressed(MenuItemPresser.java:197)
       at com.mobicage.rogerthat.plugins.friends.MenuItemPresser.itemPressed(MenuItemPresser.java:166)
       at com.mobicage.rogerthat.plugins.friends.MenuItemPresser.itemPressed(MenuItemPresser.java:161)
       at com.mobicage.rogerthat.plugins.friends.ServiceActionMenuActivity$MyPagerAdapter$1.safeOnClick(ServiceActionMenuActivity.java:749)
       at com.mobicage.rogerthat.util.system.SafeViewOnClickListener.onClick(SafeViewOnClickListener.java:32)
       at android.view.View.performClick(View.java:4463)
       at android.view.View$PerformClick.run(View.java:18770)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/commit/2b34abf8f324921f413a78c463aaa1a70171959b

**Comment by RubenMattan** [comment]
However i could't reproduce the issue itself, its looks like the user doesn't have a browser installed
