### ISSUE TITLE
Investigate why we get SQLiteConstraintException when storing new message

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#376]
```java
java.lang.RuntimeException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.key (code 1555)
       at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:89)
       at com.mobicage.rogerthat.util.db.TransactionHelper.runInTransaction(TransactionHelper.java:60)
       at com.mobicage.rogerthat.plugins.messaging.MessageStore.storeNewMessage(MessageStore.java:384)
       at com.mobicage.rogerthat.plugins.messaging.MessagingPlugin.newMessage(MessagingPlugin.java:697)
       at com.mobicage.rogerthat.plugins.messaging.MessagingCallReceiver.newMessage(MessagingCallReceiver.java:117)
       at com.mobicage.rpc.CallReceiver.processCall(CallReceiver.java:85)
       at com.mobicage.rpc.http.HttpProtocol.process(HttpProtocol.java:226)
       at com.mobicage.rpc.http.HttpProtocol.processIncomingMessagesString(HttpProtocol.java:187)
       at com.mobicage.rpc.http.HttpCommunicator$8$1.safeRun(HttpCommunicator.java:684)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#31
