### ISSUE TITLE
Failed to show notification during registration

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#377]
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mobicage.rogerthat.MainService.sendBroadcast(android.content.Intent)' on a null object reference
       at com.mobicage.rogerthat.registration.RegistrationActivity2.showNotification(RegistrationActivity2.java:248)
       at com.mobicage.rogerthat.registration.RegistrationActivity2.access$2500(RegistrationActivity2.java:110)
       at com.mobicage.rogerthat.registration.RegistrationActivity2$36$1.safeRun(RegistrationActivity2.java:1490)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#30
