### ISSUE TITLE
Failed to install payconiq app

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#378]
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.optBoolean(java.lang.String, boolean)' on a null object reference
       at com.mobicage.rogerthat.cordova.RogerthatPaymentsPlugin.installPayconiqApp(RogerthatPaymentsPlugin.java:698)
       at com.mobicage.rogerthat.cordova.RogerthatPaymentsPlugin.access$700(RogerthatPaymentsPlugin.java:92)
       at com.mobicage.rogerthat.cordova.RogerthatPaymentsPlugin$2.safeRun(RogerthatPaymentsPlugin.java:569)
       at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by RubenMattan** [comment]
Fixed by https://github.com/rogerthat-platform/cordova-rogerthat-payments-plugin/commit/e516fb6ebe3a4951a526d33e4dd3fd3e6d31273a
