### ISSUE TITLE
Error in GetBeaconRegionsResponseTO

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#393]
```
2018-06-27 08:43:08 UTC
   (0 min ago)
67e04b4f-85f6-4e12-88b7-100078f22b82
Count: 1 - Version: 2.1.3960.A
```

```
description: 

errorMessage: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
	at com.mobicage.to.beacon.GetBeaconRegionsResponseTO.<init>(GetBeaconRegionsResponseTO.java:35)
	at com.mobicage.rogerthat.registration.AbstractRegistrationWizard$1.safeDoInBackground(AbstractRegistrationWizard.java:196)
	at com.mobicage.rogerthat.registration.AbstractRegistrationWizard$1.safeDoInBackground(AbstractRegistrationWizard.java:147)
	at com.mobicage.rogerthat.util.system.SafeAsyncTask.doInBackground(SafeAsyncTask.java:44)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)


mobicageVersion: 2.1.3960.A

occurenceCount: 1

platform: 1

platformVersion: 25
```

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-android-client#27
