### ISSUE TITLE
News sender email was null

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#42]
```java

description: Bug!
Error in SafeBroadcastReceiver

errorMessage: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter$ViewHolder$1.onSafeReceive(NewsListAdapter.java:314)
	at com.mobicage.rogerthat.util.system.SafeBroadcastReceiver.onReceive(SafeBroadcastReceiver.java:61)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:997)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 0.2484

occurenceCount: 1

platform: 1

platformVersion: samsung/a3xeltexx/a3xelte:6.0.1/MMB29K/A310FXXU2BPH8:user/release-keys (-) 23 (-) SM-A310F
```

**Comment by RubenMattan** [comment]
Your news item was partial and you receive an update for that news item
