### ISSUE TITLE
Exception while loading news

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-android-client#66]
2016-11-30 08:54:51 UTC
xxx@outlook.com:be-geraardsbergen
Count: 1 - Version: 2.0.2522.A

```java

description: Uncaught exception

errorMessage: java.lang.NullPointerException: Attempt to read from field 'long com.mobicage.rogerthat.plugins.news.NewsItemIndex.id' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:1091)
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:90)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6062)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6095)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5277)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:630)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1142)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:836)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:850)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
	at android.view.View.layout(View.java:16953)
	at android.view.ViewGroup.layout(ViewGroup.java:5602)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2555)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2258)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1324)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6712)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)


mobicageVersion: 2.0.2522.A

occurenceCount: 1

platform: 1

platformVersion: 23
```

**Comment by RubenMattan** [comment]
2016-11-29 19:05:33 UTC
xxx@telenet.be
Count: 1 - Version: 2.0.2507.A

```java
description: Uncaught exception

errorMessage: java.lang.NullPointerException: Attempt to read from field 'long com.mobicage.rogerthat.plugins.news.NewsItemIndex.id' on a null object reference
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:1089)
	at com.mobicage.rogerthat.NewsListAdapter.onBindViewHolder(NewsListAdapter.java:90)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6062)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6095)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5277)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:630)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1142)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:836)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:850)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
	at android.view.View.layout(View.java:17938)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7403)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


mobicageVersion: 2.0.2507.A

occurenceCount: 1

platform: 1

platformVersion: 23
```

**Comment by FastGeert** [comment]
Ruben added loglines to understand what goes wrong when it happens. We'll need to wait until 2.0.1 is in prod to understand the problem.
